version: '3'
services:
  server:
    build: gems-manager-server/
  client:
    build: gems-manager-client/
    ports:
      - 30010:80
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dev#pass
    volumes:
    - "db_data:/var/lib/mysql"
volumes:
  db_data: {}
